### ISSUE TITLE
Business cases do not re-calculate when strategies are updated

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#513]
See LES 313 for example.

**Comment by grdw** [comment]
Since this is only - not working on the production environment - the most easy fix would be to merge all the changes that are related to the business cases to the production environemnt.

**Comment by antw** [comment]
Can we identify the issue and cherry-pick the relevant commit onto the production branch? I think we should have another production deploy of Moses soon, but this would be good enough for the short-term.

**Comment by grdw** [comment]
> Can we identify the issue and cherry-pick the relevant commit onto the production branch?

Yes. That's basically what I was trying to say.

**Comment by ChaelKruip** [comment]
@dennisschoenmakers is doing a demo at the moment. Please wait an hour or so before deploying production!

**Comment by antw** [comment]
The problem is that the Moses scenario points to ETEngine scenario 434138. ETEngine has no such scenario.

ETEngine *production* scenarios are currently numbered in the 200,000s, while *staging* is in the 400,000s. I'm not clear how production Moses could take scenarios from staging ETEngine, and I'm sure I deleted all the scenarios on Moses production during the deploy last week.

The `created_at` field is "2015-09-27 13:24:33" which is three days *before* the deploy. Did these scenarios get imported manually somehow?

```
404 Resource Not Found
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:853:in `start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/rest-client-1.6.7/lib/restclient.rb:68:in `get'
/var/www/etmoses/releases/20150930151452/lib/et_engine_connector.rb:67:in `public_send'
/var/www/etmoses/releases/20150930151452/lib/et_engine_connector.rb:67:in `et_api_request'
/var/www/etmoses/releases/20150930151452/lib/et_engine_connector.rb:42:in `merit'
/var/www/etmoses/releases/20150930151452/app/models/market/from_market_model_builder.rb:63:in `merit_curve'
/var/www/etmoses/releases/20150930151452/app/models/market/from_market_model_builder.rb:54:in `convert_tariff'
/var/www/etmoses/releases/20150930151452/app/models/market/from_market_model_builder.rb:33:in `block in relations'
/var/www/etmoses/releases/20150930151452/app/models/market/from_market_model_builder.rb:27:in `map'
/var/www/etmoses/releases/20150930151452/app/models/market/from_market_model_builder.rb:27:in `relations'
/var/www/etmoses/releases/20150930151452/app/models/market/from_market_model_builder.rb:18:in `data'
/var/www/etmoses/releases/20150930151452/app/models/market/from_market_model_builder.rb:11:in `to_market'
/var/www/etmoses/releases/20150930151452/app/models/market.rb:59:in `from_market_model'
/var/www/etmoses/releases/20150930151452/app/services/finance/business_case_calculator.rb:40:in `market'
/var/www/etmoses/releases/20150930151452/app/services/finance/business_case_calculator.rb:32:in `row'
/var/www/etmoses/releases/20150930151452/app/services/finance/business_case_calculator.rb:23:in `block in cells'
/var/www/etmoses/releases/20150930151452/app/services/finance/business_case_calculator.rb:21:in `map'
/var/www/etmoses/releases/20150930151452/app/services/finance/business_case_calculator.rb:21:in `cells'
/var/www/etmoses/releases/20150930151452/app/services/finance/business_case_calculator.rb:10:in `block in rows'
/var/www/etmoses/releases/20150930151452/app/services/finance/business_case_calculator.rb:9:in `map'
/var/www/etmoses/releases/20150930151452/app/services/finance/business_case_calculator.rb:9:in `rows'
/var/www/etmoses/releases/20150930151452/app/services/finance/business_case_creator.rb:16:in `financials'
/var/www/etmoses/releases/20150930151452/app/services/finance/business_case_creator.rb:10:in `calculate'
/var/www/etmoses/releases/20150930151452/app/jobs/business_case_calculator_job.rb:12:in `perform'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/timeout.rb:101:in `call'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:124:in `run'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:112:in `block in run_process'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:265:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:265:in `block in start_proc'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/daemonize.rb:84:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/daemonize.rb:84:in `call_as_daemon'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:269:in `start_proc'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:295:in `start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/controller.rb:56:in `run'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons.rb:193:in `block in run_proc'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `catch_exceptions'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons.rb:192:in `run_proc'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:110:in `run_process'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:91:in `block in daemonize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in `times'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in `daemonize'
bin/delayed_job:5:in `<main>'
```

**Comment by grdw** [comment]
> Did these scenarios get imported manually somehow?

Yes.

**Comment by ChaelKruip** [comment]
Closing.

**Comment by ChaelKruip** [comment]
@grdw please remove the offending LESses again from the production database to prevent future issues.
