### ISSUE TITLE
Business case not calculating correctly for LES#id=332

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#542]
Delayed job is having a problem trying to calculate the business case with a merit curve.

````
Tried to price a value collection containing 0 values with a curve containing 35040
/var/www/etmoses/releases/20151019103323/app/models/market/curve_tariff.rb:14:in `price_of'
/var/www/etmoses/releases/20151019103323/app/models/market/payment_rule.rb:28:in `call'
/var/www/etmoses/releases/20151019103323/app/models/market/relation.rb:27:in `price'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/core_ext/enumerable.rb:22:in `map'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/core_ext/enumerable.rb:22:in `sum'
/var/www/etmoses/releases/20151019103323/app/services/finance/business_case_calculator.rb:36:in `row'
/var/www/etmoses/releases/20151019103323/app/services/finance/business_case_calculator.rb:26:in `block in cells'
/var/www/etmoses/releases/20151019103323/app/services/finance/business_case_calculator.rb:21:in `map'
/var/www/etmoses/releases/20151019103323/app/services/finance/business_case_calculator.rb:21:in `cells'
/var/www/etmoses/releases/20151019103323/app/services/finance/business_case_calculator.rb:10:in `block in rows'
/var/www/etmoses/releases/20151019103323/app/services/finance/business_case_calculator.rb:9:in `map'
/var/www/etmoses/releases/20151019103323/app/services/finance/business_case_calculator.rb:9:in `rows'
/var/www/etmoses/releases/20151019103323/app/services/finance/business_case_creator.rb:16:in `financials'
/var/www/etmoses/releases/20151019103323/app/services/finance/business_case_creator.rb:10:in `calculate'
/var/www/etmoses/releases/20151019103323/app/jobs/business_case_calculator_job.rb:12:in `perform'
````

**Comment by grdw** [comment]
@antw is this by any chance fixed with 95a9c80 ? :pray:
