### ISSUE TITLE
Toggling concurrency to all min and applying breaks the concurrency toggle

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#545]
If I try to toggle back to 'min' and apply I get an internal sever error (500) for [this LES](http://beta.moses.et-model.com/testing_grounds/334)

**Comment by grdw** [comment]
Posting backtrace:

````
App backtrace
-------------

 - app/models/installed_technology.rb:105:in `electrical_capacity='
 - app/models/installed_technology.rb:138:in `performance_coefficient='
 - app/models/technology_list.rb:26:in `block (2 levels) in from_hash'
 - app/models/technology_list.rb:25:in `block in from_hash'
 - app/models/technology_list.rb:24:in `from_hash'
 - app/controllers/testing_grounds_controller.rb:129:in `calculate_concurrency'
 - bin/rails:8:in `<top (required)>'
 - bin/spring:16:in `<top (required)>'
````
