### ISSUE TITLE
Turbine::DuplicateEdgeError: Another edge already exists on #<Market::Stakeholder key="supplier"> which is too similar to #<Market::Relation #<Market::PaymentRule:0x007f1abd314b18>>

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#570]
Check full details on Airbrake: [#1539751509869704816](https://quintel.airbrake.io/projects/111227/groups/1539751509869704816)

Backtrace:
```
[GEM_ROOT]/gems/turbine-graph-0.1.3/lib/turbine/node.rb:228:in connect_endpoint
[GEM_ROOT]/gems/turbine-graph-0.1.3/lib/turbine/node.rb:187:in connect_via
[PROJECT_ROOT]/app/models/market/stakeholder.rb:12:in block in connect_to
[PROJECT_ROOT]/app/models/market/stakeholder.rb:11:in tap
[PROJECT_ROOT]/app/models/market/stakeholder.rb:11:in connect_to
[PROJECT_ROOT]/app/models/market/builder.rb:71:in build_relation!
[PROJECT_ROOT]/app/models/market/builder.rb:50:in block in to_market
[PROJECT_ROOT]/app/models/market/builder.rb:49:in each
[PROJECT_ROOT]/app/models/market/builder.rb:49:in to_market
[PROJECT_ROOT]/app/models/market/from_market_model_builder.rb:11:in to_market
[PROJECT_ROOT]/app/models/market.rb:59:in from_market_model
[PROJECT_ROOT]/app/services/finance/business_case_calculator.rb:40:in market
[PROJECT_ROOT]/app/services/finance/business_case_calculator.rb:32:in row
[PROJECT_ROOT]/app/services/finance/business_case_calculator.rb:23:in block in cells
[PROJECT_ROOT]/app/services/finance/business_case_calculator.rb:21:in map
[PROJECT_ROOT]/app/services/finance/business_case_calculator.rb:21:in cells
[PROJECT_ROOT]/app/services/finance/business_case_calculator.rb:10:in block in rows
[PROJECT_ROOT]/app/services/finance/business_case_calculator.rb:9:in map
[PROJECT_ROOT]/app/services/finance/business_case_calculator.rb:9:in rows
[PROJECT_ROOT]/app/services/finance/business_case_creator.rb:16:in financials
[PROJECT_ROOT]/app/services/finance/business_case_creator.rb:10:in calculate
[PROJECT_ROOT]/app/jobs/business_case_calculator_job.rb:12:in perform
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in block in invoke_job
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in call
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in block in initialize
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in call
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in execute
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in run_callbacks
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in invoke_job
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in block (2 levels) in run
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/timeout.rb:91:in block in timeout
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/timeout.rb:101:in call
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/timeout.rb:101:in timeout
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in block in run
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/benchmark.rb:294:in realtime
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in run
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in block in reserve_and_run_one_job
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in call
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in block in initialize
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in call
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in execute
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in run_callbacks
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in reserve_and_run_one_job
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in block in work_off
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in times
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in work_off
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in block (4 levels) in start
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/benchmark.rb:294:in realtime
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in block (3 levels) in start
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in call
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in block in initialize
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in call
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in execute
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in run_callbacks
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in block (2 levels) in start
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in loop
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in block in start
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in call
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in block (2 levels) in <class:ClearLocks>
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in call
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in block (2 levels) in add
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in call
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in block in initialize
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in call
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in block in add
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in call
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in execute
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in run_callbacks
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in start
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/command.rb:124:in run
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/command.rb:112:in block in run_process
[GEM_ROOT]/gems/daemons-1.2.2/lib/daemons/application.rb:265:in call
[GEM_ROOT]/gems/daemons-1.2.2/lib/daemons/application.rb:265:in block in start_proc
[GEM_ROOT]/gems/daemons-1.2.2/lib/daemons/daemonize.rb:84:in call
[GEM_ROOT]/gems/daemons-1.2.2/lib/daemons/daemonize.rb:84:in call_as_daemon
[GEM_ROOT]/gems/daemons-1.2.2/lib/daemons/application.rb:269:in start_proc
[GEM_ROOT]/gems/daemons-1.2.2/lib/daemons/application.rb:295:in start
[GEM_ROOT]/gems/daemons-1.2.2/lib/daemons/application_group.rb:151:in block (2 levels) in start_all
[GEM_ROOT]/gems/daemons-1.2.2/lib/daemons/application_group.rb:150:in fork
[GEM_ROOT]/gems/daemons-1.2.2/lib/daemons/application_group.rb:150:in block in start_all
[GEM_ROOT]/gems/daemons-1.2.2/lib/daemons/application_group.rb:149:in each
[GEM_ROOT]/gems/daemons-1.2.2/lib/daemons/application_group.rb:149:in start_all
[GEM_ROOT]/gems/daemons-1.2.2/lib/daemons/controller.rb:66:in run
[GEM_ROOT]/gems/daemons-1.2.2/lib/daemons.rb:193:in block in run_proc
[GEM_ROOT]/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in call
[GEM_ROOT]/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in catch_exceptions
[GEM_ROOT]/gems/daemons-1.2.2/lib/daemons.rb:192:in run_proc
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/command.rb:110:in run_process
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/command.rb:91:in block in daemonize
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in times
[GEM_ROOT]/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in daemonize
bin/delayed_job:5:in <main>
```

**Comment by antw** [comment]
https://github.com/quintel/etmoses/issues/449#issuecomment-143188949

**Comment by grdw** [comment]
Including: https://github.com/quintel/etmoses/issues/734

Was this fix also merged to production? 

Delayed Job is complaining about something similar: 

````
Another edge already exists on #<Market::Stakeholder key="customer AC6"> which is too similar to #<Market::Relation "customer AC6" -:kw_max-➤ "system operator">
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/turbine-graph-0.1.3/lib/turbine/node.rb:228:in `connect_endpoint'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/turbine-graph-0.1.3/lib/turbine/node.rb:187:in `connect_via'
/var/www/etmoses/releases/20160119153256/app/models/market/stakeholder.rb:12:in `block in connect_to'
/var/www/etmoses/releases/20160119153256/app/models/market/stakeholder.rb:11:in `tap'
/var/www/etmoses/releases/20160119153256/app/models/market/stakeholder.rb:11:in `connect_to'
/var/www/etmoses/releases/20160119153256/app/models/market/builder.rb:74:in `build_relation!'
/var/www/etmoses/releases/20160119153256/app/models/market/builder.rb:53:in `block in to_market'
/var/www/etmoses/releases/20160119153256/app/models/market/builder.rb:52:in `each'
/var/www/etmoses/releases/20160119153256/app/models/market/builder.rb:52:in `to_market'
/var/www/etmoses/releases/20160119153256/app/models/market/from_market_model_builder.rb:11:in `to_market'
/var/www/etmoses/releases/20160119153256/app/models/market.rb:59:in `from_market_model'
/var/www/etmoses/releases/20160119153256/app/services/finance/business_case_calculator.rb:52:in `market'
/var/www/etmoses/releases/20160119153256/app/services/finance/business_case_calculator.rb:43:in `row'
/var/www/etmoses/releases/20160119153256/app/services/finance/business_case_calculator.rb:34:in `block in cells'
/var/www/etmoses/releases/20160119153256/app/services/finance/business_case_calculator.rb:32:in `map'
/var/www/etmoses/releases/20160119153256/app/services/finance/business_case_calculator.rb:32:in `cells'
/var/www/etmoses/releases/20160119153256/app/services/finance/business_case_calculator.rb:10:in `block in rows'
/var/www/etmoses/releases/20160119153256/app/services/finance/business_case_calculator.rb:9:in `map'
/var/www/etmoses/releases/20160119153256/app/services/finance/business_case_calculator.rb:9:in `rows'
/var/www/etmoses/releases/20160119153256/app/services/finance/business_case_creator.rb:16:in `financials'
/var/www/etmoses/releases/20160119153256/app/services/finance/business_case_creator.rb:10:in `calculate'
/var/www/etmoses/releases/20160119153256/app/jobs/business_case_calculator_job.rb:12:in `perform'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/timeout.rb:101:in `call'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:124:in `run'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:112:in `block in run_process'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:265:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:265:in `block in start_proc'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/daemonize.rb:84:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/daemonize.rb:84:in `call_as_daemon'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:269:in `start_proc'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:295:in `start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application_group.rb:151:in `block (2 levels) in start_all'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application_group.rb:150:in `fork'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application_group.rb:150:in `block in start_all'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application_group.rb:149:in `each'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application_group.rb:149:in `start_all'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/controller.rb:66:in `run'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons.rb:193:in `block in run_proc'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `catch_exceptions'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons.rb:192:in `run_proc'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:110:in `run_process'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:91:in `block in daemonize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in `times'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in `daemonize'
bin/delayed_job:5:in `<main>'
````

Could be completley unrelated ofcourse.

**Comment by antw** [comment]
[The limitation](https://github.com/quintel/etmoses/issues/734#issuecomment-178522149) is still present on the master branch (so beta and production). I'll see what I can do to resolve this – this week or next – depending on how much remains for the deploy.
