### ISSUE TITLE
LES refused to calculate?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#658]
![image](https://cloud.githubusercontent.com/assets/104830/11690551/86621bf2-9e97-11e5-9625-66fab88ba7b1.png)

LES created by @JeroenvdLogt.

**Comment by ChaelKruip** [comment]
Re-assigning to @grdw

**Comment by antw** [comment]
FYI: DelayedJob exception:

```
undefined method `update_column' for nil:NilClass
/var/www/etmoses/releases/20151204094938/app/jobs/testing_ground_calculator_job.rb:15:in `success'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:114:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:114:in `hook'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:95:in `block in invoke_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/timeout.rb:101:in `call'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:124:in `run'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:112:in `block in run_process'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:265:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:265:in `block in start_proc'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/daemonize.rb:84:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/daemonize.rb:84:in `call_as_daemon'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:269:in `start_proc'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:295:in `start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application_group.rb:151:in `block (2 levels) in start_all'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application_group.rb:150:in `fork'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application_group.rb:150:in `block in start_all'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application_group.rb:149:in `each'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application_group.rb:149:in `start_all'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/controller.rb:66:in `run'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons.rb:193:in `block in run_proc'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `catch_exceptions'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons.rb:192:in `run_proc'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:110:in `run_process'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:91:in `block in daemonize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in `times'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in `daemonize'
bin/delayed_job:5:in `<main>'
```

https://github.com/quintel/etmoses/blob/2afdeef4b41dcda9c77dd7a92508f37b30c05c96/app/jobs/testing_ground_calculator_job.rb#L14-L15

**Comment by grdw** [comment]
I see. I deleted the corresponding `testing_ground_delayed_job` and it started running again.

**Comment by grdw** [comment]
Follow up: https://github.com/quintel/etmoses/issues/660 

I'll try to fix this. I'm guessing that because of the time, somebody breaks off the request and starts a new which causes this `NilClass` error

**Comment by antw** [comment]
I *think* changing TestingGroundDelayedJob#for to use `where(type: type)` instead of `find_by` would solve this. But it will return an array of matching records instead of the first record, so other code may be affected.

**Comment by JeroenvdLogt** [comment]
I think this issue could be mitigated if there will be a button to start calculations manually. Many times, as user, I want to switch between simulation results and the editing page without recalculation. The same holds for when I start a LES from the LES list. Many times it is enough to see results and settings. When I am ready with all changes I should be able to start calculations manually. 

I think this will prevent users to abort calculations with the purpose to see and adjust settings.
