### ISSUE TITLE
LES scenarios do not load on live server

### ISSUE THREAD

**Issue by wouterterlouw** [quintel/etmoses#724]
My scenario (http://moses.et-model.com/testing_grounds/362) doesn't load on the live server:

![image](https://cloud.githubusercontent.com/assets/4319656/12174121/0d54c46e-b55b-11e5-8ec0-51ce9ea41eb4.png)

This also happens with other scenarios... (e.g. http://moses.et-model.com/testing_grounds/378).

**Comment by grdw** [comment]
Hmm. I removed all old 'stuck' delayed jobs and it now seems to work. Thanks for notifying :+1:

**Comment by grdw** [comment]
-> https://github.com/quintel/etmoses/issues/711 This bug does pop up though.

Backtrace:

````
key not found: "default"
/var/www/etmoses/releases/20151217131900/app/models/calculation/technology_load.rb:68:in `fetch'
/var/www/etmoses/releases/20151217131900/app/models/calculation/technology_load.rb:68:in `block in comps_for'
/var/www/etmoses/releases/20151217131900/app/models/calculation/technology_load.rb:64:in `each'
/var/www/etmoses/releases/20151217131900/app/models/calculation/technology_load.rb:64:in `each_with_object'
/var/www/etmoses/releases/20151217131900/app/models/calculation/technology_load.rb:64:in `comps_for'
/var/www/etmoses/releases/20151217131900/app/models/calculation/technology_load.rb:19:in `block in run'
/var/www/etmoses/releases/20151217131900/app/models/calculation/technology_load.rb:18:in `each'
/var/www/etmoses/releases/20151217131900/app/models/calculation/technology_load.rb:18:in `run'
/var/www/etmoses/releases/20151217131900/app/models/calculation/technology_load.rb:4:in `call'
/var/www/etmoses/releases/20151217131900/app/models/testing_ground.rb:68:in `block in to_calculated_graphs'
/var/www/etmoses/releases/20151217131900/app/models/testing_ground.rb:67:in `each'
/var/www/etmoses/releases/20151217131900/app/models/testing_ground.rb:67:in `reduce'
/var/www/etmoses/releases/20151217131900/app/models/testing_ground.rb:67:in `to_calculated_graphs'
/var/www/etmoses/releases/20151217131900/app/jobs/testing_ground_calculator_job.rb:8:in `perform'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/timeout.rb:101:in `call'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:124:in `run'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:112:in `block in run_process'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:265:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:265:in `block in start_proc'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/daemonize.rb:84:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/daemonize.rb:84:in `call_as_daemon'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:269:in `start_proc'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:295:in `start'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application_group.rb:151:in `block (2 levels) in start_all'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application_group.rb:150:in `fork'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application_group.rb:150:in `block in start_all'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application_group.rb:149:in `each'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application_group.rb:149:in `start_all'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/controller.rb:66:in `run'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons.rb:193:in `block in run_proc'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `catch_exceptions'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons.rb:192:in `run_proc'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:110:in `run_process'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:91:in `block in daemonize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in `times'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in `daemonize'
bin/delayed_job:5:in `<main>'
````

**Comment by grdw** [comment]
Including @antw

**Comment by antw** [comment]
> This bug does pop up though. [...] key not found: "default"

Fixed. Old profiles had been assigned to the hot water buffers; shouldn't happen again.
