### ISSUE TITLE
No comparison between business cases

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#803]
I am trying to compare one BC with another in the dashboard interface of ET-Moses. But it doesn't work on the production server. In the beta server it works fine.
![geen vergelijking van winst- en verliesrekening](https://cloud.githubusercontent.com/assets/7781037/13144085/9e63a12e-d648-11e5-8593-7a1b1c45c7d7.JPG)

**Comment by ChaelKruip** [comment]
@grdw can you look into this?

@JeroenvdLogt can you please include a link to the LES?

**Comment by JeroenvdLogt** [comment]
Compare business case from USEF Lochem 2050 with USEF: doorrekening Lochem 2025 referentie

http://etmoses.et-model.com/testing_grounds/395

**Comment by grdw** [comment]
"USEF: doorrekening Lochem 2025 referentie" business case is never calculated so there's nothing to compare with. I'm currently recalculating those business cases. The background processor cue is momentarely a bit full.

**Comment by grdw** [comment]
Related error in Job cue:
````
Cannot interpolate a curve with 1 values to 8760
/var/www/etmoses/releases/20160211152355/app/models/market/interpolated_curve.rb:14:in `new'
/var/www/etmoses/releases/20160211152355/app/models/market/merit_builder.rb:32:in `price_curve'
/var/www/etmoses/releases/20160211152355/app/models/market/from_market_model_builder.rb:54:in `convert_tariff'
/var/www/etmoses/releases/20160211152355/app/models/market/from_market_model_builder.rb:33:in `block in relations'
/var/www/etmoses/releases/20160211152355/app/models/market/from_market_model_builder.rb:27:in `map'
/var/www/etmoses/releases/20160211152355/app/models/market/from_market_model_builder.rb:27:in `relations'
/var/www/etmoses/releases/20160211152355/app/models/market/from_market_model_builder.rb:18:in `data'
/var/www/etmoses/releases/20160211152355/app/models/market/from_market_model_builder.rb:11:in `to_market'
/var/www/etmoses/releases/20160211152355/app/models/market.rb:59:in `from_market_model'
/var/www/etmoses/releases/20160211152355/app/services/finance/business_case_calculator.rb:52:in `market'
/var/www/etmoses/releases/20160211152355/app/services/finance/business_case_calculator.rb:43:in `row'
/var/www/etmoses/releases/20160211152355/app/services/finance/business_case_calculator.rb:34:in `block in cells'
/var/www/etmoses/releases/20160211152355/app/services/finance/business_case_calculator.rb:32:in `map'
/var/www/etmoses/releases/20160211152355/app/services/finance/business_case_calculator.rb:32:in `cells'
/var/www/etmoses/releases/20160211152355/app/services/finance/business_case_calculator.rb:10:in `block in rows'
/var/www/etmoses/releases/20160211152355/app/services/finance/business_case_calculator.rb:9:in `map'
/var/www/etmoses/releases/20160211152355/app/services/finance/business_case_calculator.rb:9:in `rows'
/var/www/etmoses/releases/20160211152355/app/services/finance/business_case_creator.rb:16:in `financials'
/var/www/etmoses/releases/20160211152355/app/services/finance/business_case_creator.rb:10:in `calculate'
/var/www/etmoses/releases/20160211152355/app/jobs/business_case_calculator_job.rb:12:in `perform'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
...
/var/www/etmoses/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in `daemonize'
bin/delayed_job:5:in `<main>'
````

**Comment by antw** [comment]
> @antw do you know what this error is saying?

Probably something that isn't a curve (1 element long) being priced using the merit order curve (8760 elements long). I'll take a look into it.

**Comment by antw** [comment]
LES 365 is very broken. Every technology in the LES looks like this:

```js
{
  "node": null,
  "name": "Residential PV panel",      // <- !!!
  "buffer": null,
  "composite": false,
  "composite_index": null,
  "composite_value": null,
  "position_relative_to_buffer": null,
  "type": "generic",                   // <- !!!
  "behavior": null,
  "profile": null,                     // <- !!!
  "profile_key": null,                 // <- !!!
  "capacity": -1.5,
  "demand": null,
  "volume": null,
  "units": 385,
  "initial_investment": null,
  "technical_lifetime": null,
  "performance_coefficient": 1.0,
  "concurrency": "max",
  "full_load_hours": null,
  "om_costs_per_year": null,
  "om_costs_per_full_load_hour": null,
  "om_costs_for_ccs_per_full_load_hour": null,
  "associates": [],
  "includes": []
},
```

Every technology is a `generic` and has no profile (hence they have only a single instantaneous load which is what triggers the "Cannot interpolate a curve with **1** values to 8760" error when computing the market model).

I'm not sure how this could have happened. No other LES is like this. :confused:

**Comment by grdw** [comment]
> I'm not sure how this could have happened. No other LES is like this.

I can remember an issue with the CSV export once that did this...

**Comment by grdw** [comment]
We can fix this LES by updating all the types to the correct one's and selecting the default profiles. I'll see what I can manage to repair.

**Comment by grdw** [comment]
What I've done so far is assign is the correct type + default profile and profile key; that's it. The LES now shows load + a business case: http://moses.et-model.com/testing_grounds/361
