### ISSUE TITLE
Airbrake broken (https?)

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#821]
````
E, [2016-02-29T10:33:42.706167 #5014] ERROR -- : ** [Airbrake] [Airbrake::Sender#send_to_airbrake] Cannot send notification. Error: Errno::EPIPE - Broken pipe
Backtrace:
/home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/protocol.rb:211:in `write'
        /home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/protocol.rb:211:in `write0'
        /home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/protocol.rb:185:in `block in write'
        /home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/protocol.rb:202:in `writing'
        /home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/protocol.rb:184:in `write'
        /home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http/generic_request.rb:184:in `send_request_with_body'
        /home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http/generic_request.rb:130:in `exec'
        /home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:1406:in `block in transport_request'
        /home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
        /home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
        /home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:1378:in `request'
        /var/www/etmoses/shared/bundle/ruby/2.1.0/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
        /home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:1371:in `block in request'
        /home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:853:in `start'
        /home/ubuntu/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:1369:in `request'
````

**Comment by grdw** [comment]
This is weird. The command: `rake airbrake:test` works. I'll investigate a little further.

**Comment by grdw** [comment]
Also triggering them from the command line doesn't cause any problems. 

I'll keep this issue open in case no Airbrake messages seem to appear. It could also just be a one-time only problem from #820.

**Comment by antw** [comment]
I think this can be closed as messages have arrived at Airbrake today.
